CREATE TABLE `product` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `category_id` int(11) DEFAULT NULL COMMENT '分类id',
   `category_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分类名称',
   `brand_id` int(11) DEFAULT NULL COMMENT '品牌id',
   `name` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品名称',
   `code` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品编号',
   `bar_code` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品条码',
   `create_date` datetime DEFAULT current_timestamp() COMMENT '商品添加日期',
   `update_date` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '商品最后更新日期',
   `is_del` int(11) DEFAULT 0 COMMENT '是否删除',
   `is_group` int(11) DEFAULT 0 COMMENT '已经弃用此字段，用product_type判断商品是否为组合商品',
   `pic` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品图片（多图）',
   `selling_point` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品卖点',
   `video` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品视频地址',
   `content_pc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '电脑端详情内容',
   `content_mobile` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机端详情内容',
   `is_discount` int(11) DEFAULT NULL COMMENT '是否参与优惠折扣',
   `product_type` int(11) DEFAULT NULL COMMENT '商品类别（1-实物商品，2-虚拟商品，3-组合商品）',
   `is_use` int(11) DEFAULT 0 COMMENT '商品是否被使用过（认领或者其它第三方使用，否则不能被删除商品本身及SKU）',
   `del_date` datetime DEFAULT NULL COMMENT '删除时间',
   `channel_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '渠道id，多渠道用逗号分隔',
   `is_drugs` int(11) DEFAULT 0 COMMENT '是否为药品 0否，1是',
   `use_range` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '商品应用范围（1电商，2前置仓，3门店仓）,多个用,分隔',
   `group_type` int(11) NOT NULL DEFAULT 0 COMMENT '组合类型(1:实实组合,2:虚虚组合,3.虚实组合)只有是组合商品才有值',
   `term_type` int(11) NOT NULL DEFAULT 0 COMMENT '只有虚拟商品才有值(1.有效期至多少  2.有效期天数)',
   `term_value` int(11) NOT NULL DEFAULT 0 COMMENT '如果term_type=1 存：时间戳  如果term_type=2 存多少天',
   `virtual_invalid_refund` int(11) NOT NULL DEFAULT 0 COMMENT '是否支持过期退款 1：是  0：否',
   `warehouse_type` int(11) DEFAULT 0 COMMENT '药品仓类型：0:默认否, 1:巨星药品仓',
   `del_use` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '删除人',
   `is_intel_goods` int(11) DEFAULT 0 COMMENT '是否互联网医疗商品（1是，0否）',
   `disabled` int(11) DEFAULT 0 COMMENT '商品的状态，0：oms启用，1：oms禁用',
   `spec_value` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '规格值',
   `org_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '组织code',
   `org_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '组织名称',
   `org_id` int(11) DEFAULT 0 COMMENT '组织id',
   `centralize_purchase_id` int(11) DEFAULT NULL COMMENT ' 集采类型名称 （0：全国集采 ，1：区域集采，2：非集采）',
   PRIMARY KEY (`id`) USING BTREE,
   KEY `product_brand_id_IDX` (`brand_id`) USING BTREE
) ENGINE=InnoDB  COMMENT='商品库'